apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: seldon-cluster-manager-server
  app.kubernetes.io/component: seldon-core-operator
  app.kubernetes.io/name: seldon-core
  component: seldon-core

images:
- name: seldonio/cluster-manager
  newTag: 0.2.7

resources:
# The full spec needs the bugfix https://github.com/kubernetes-sigs/kustomize/pull/911 to be released
#- machinelearning_v1alpha2_seldondeployment_full.yaml
- machinelearning_v1alpha2_seldondeployment.yaml
- seldon-core-seldon-cluster-manager-deploy.yaml
- seldon-sa.yaml

configMapGenerator:
- name: seldon-config
  literals:
    - engineImage=seldonio/engine:0.2.7    
    - singleNamespace=true
