apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: seldondeployments.machinelearning.seldon.io
spec:
  group: machinelearning.seldon.io
  names:
    kind: SeldonDeployment
    plural: seldondeployments
    shortNames:
    - sdep
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            annotations:
              type: object
            name:
              type: string
            predictors:
              items:
                properties:
                  annotations:
                    type: object
                  componentSpecs:
                    items:
                      properties:
                        hpaSpec:
                          properties:
                            maxReplicas:
                              format: int32
                              type: integer
                            metrics:
                              items:
                                type: object
                              type: array
                            minReplicas:
                              format: int32
                              type: integer
                          type: object
                        metadata:
                          type: object
                        spec:
                          type: object
                      type: object
                    type: array
                  engineResources:
                    type: object
                  graph:
                    properties:
                      children:
                        items:
                          type: object
                        type: array
                      endpoint:
                        properties:
                          type:
                            type: string
                        type: object
                      implementation:
                        type: string
                      methods:
                        items:
                          type: string
                        type: array
                      name:
                        type: string
                      parameters:
                        items:
                          properties:
                            name:
                              type: string
                            type:
                              type: string
                            value:
                              type: string
                          type: object
                        type: array
                      type:
                        type: string
                    type: object
                  labels:
                    type: object
                  name:
                    type: string
                  replicas:
                    format: int32
                    type: integer
                  svcOrchSpec:
                    properties:
                      env:
                        items:
                          type: object
                        type: array
                      resources:
                        type: object
                    type: object
                  traffic:
                    format: int32
                    type: integer
                type: object
              type: array
          type: object
        status:
          properties:
            deploymentStatus:
              type: object
            description:
              type: string
            serviceStatus:
              type: object
            state:
              type: string
          type: object
  version: v1alpha2
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
