apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: seldon-local
rules:
- apiGroups:
  - '*'
  resources:
  - deployments
  - services
  - horizontalpodautoscalers
  verbs:
  - '*'
- apiGroups:
  - machinelearning.seldon.io
  resources:
  - '*'
  verbs:
  - '*'
