apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: seldon-core-seldon-cluster-manager
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: SELDON_CLUSTER_MANAGER_REDIS_HOST
          value: seldon-core-redis-master
        - name: ENGINE_CONTAINER_IMAGE_AND_VERSION
          valueFrom:
            configMapKeyRef:
              name: seldon-config
              key: engineImage
        - name: ENGINE_CONTAINER_IMAGE_PULL_POLICY
          value: IfNotPresent
        - name: ENGINE_CONTAINER_SERVICE_ACCOUNT_NAME
          value: default
        - name: SELDON_CLUSTER_MANAGER_SINGLE_NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: seldon-config
              key: singleNamespace
        - name: ENGINE_CONTAINER_USER
          value: "8888"
        - name: PREDICTIVE_UNIT_SERVICE_PORT
          value: "9000"
        - name: ENGINE_SERVER_GRPC_PORT
          value: "5001"
        - name: ENGINE_SERVER_PORT
          value: "8000"
        - name: ENGINE_PROMETHEUS_PATH
          value: prometheus
        - name: SELDON_CLUSTER_MANAGER_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: seldonio/cluster-manager:0.2.7
        imagePullPolicy: IfNotPresent
        name: seldon-cluster-manager-container
        ports:
        - containerPort: 8080
          protocol: TCP
        securityContext:
          runAsUser: 8888
      serviceAccountName: seldon
      terminationGracePeriodSeconds: 1
