apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: seldon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: seldon-local
subjects:
- kind: ServiceAccount
  name: seldon
