apiVersion: apps/v1
kind: Deployment
metadata:
  name: seldon-controller-manager
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
      - env:
        - name: ISTIO_GATEWAY
          value: kubeflow/kubeflow-gateway
        name: manager

